// apps/splash-2025/src/components/footer.tsx
import type { ReactNode } from "react";
import { FooterWave } from "./icons";
import { SoMeLinks } from "./someLinks";

export const Footer = ({ sponsorLogo }: { sponsorLogo?: ReactNode }) => {
	return (
		<footer className="text-white bg-brand">
			<div className="overflow-hidden">
				<FooterWave color="#C1842E" className="size-[135%]" />
			</div>
			<div className="bg-[#C1842E] flex flex-col items-center pb-4">
				<h5 className="text-4xl m-3 mt-0">Har du noen spørsmål?</h5>
				<p className="text-xl text-center mx-4">
					Dersom du lurer på noe, ikke nøl med å ta kontakt! Du kan nå oss på{" "}
					<a href="mailto:kontakt@online.ntnu.no" className="underline">
						kontakt@online.ntnu.no
					</a>
				</p>
				<SoMeLinks />
			</div>

			{sponsorLogo && (
				<div className="overflow-hidden">
					<div className="bg-[#C1842E] ">
						<FooterWave
							color="#F9B759"
							className="h-[100%] w-[135%] relative left-[-30%]"
						/>
					</div>
					<div className="bg-[#F9B759] flex justify-center p-10">
						{sponsorLogo}
					</div>
				</div>
			)}
		</footer>
	);
};

// apps/splash/src/components/Footer.svelte
<script lang="ts">
  import { FacebookIcon, InstagramIcon, GithubIcon } from "svelte-feather-icons"

  const email = "kontakt@online.ntnu.no"
</script>

<footer class="bg-slate-1">
  <div class="flex flex-col items-center justify-center w-11/12 md:w-3/5">
    <div>
      <h2>Har du noen spørsmål?</h2>
      <div>
        <span
          >Dersom du lurer på noe, ikke nøl med å ta kontakt! Du kan nå oss på{" "}
          <a href={`mailto:${email}`}>{email}</a>.
        </span>
      </div>
    </div>

    <div class="flex space-x-2 justify-center items-center">
      <FacebookIcon class="w-8 h-8" />
      <InstagramIcon class="w-8 h-8" />
      <GithubIcon class="w-8 h-8" />
    </div>
  </div>
</footer>

<style>
  footer {
    @apply relative mt-auto flex min-h-[10rem] w-full flex-col items-center justify-center py-8;
  }
</style>
