// apps/splash-2025/src/components/hero.tsx
import type { FC } from "react"
import type { HeroProps } from "../data/hero"

export const Hero: FC<HeroProps> = ({ background, banner }) => {
  return (
    <div
      className={`${background} h-screen bg-no-repeat bg-cover bg-center max-md:p-16 p-32 flex flex-col justify-center items-center text-white`}
    >
      <img src={banner} alt="Logo for Online's fadderuker" className="scale-75" />
      <h3 className="max-md:text-2xl text-4xl mb-5 text-center">
        Velkommen til Online, linjeforeningen for informatikkstudenter ved NTNU!
      </h3>
      <p className="text-center md:text-lg">
        Det er vi som sørger for at studietiden blir den beste tiden i ditt liv! Vi i Online arrangerer utflukter,
        turer, fester, holder kurs og bedriftspresentasjoner gjennom hele året.
        <br />
        Ny på master? Se{" "}
        <a href="https://online.ntnu.no" className="underline text-brand-8">
          viktig info om IT-ekskursjonen
        </a>{" "}
        OBS - kort frist!
      </p>
    </div>
  )
}

// apps/splash/src/components/sections/Hero.svelte
<script lang="ts">
  import Link from "../common/Link.svelte"
</script>

<div class="flex flex-col justify-center items-center space-y-4 w-3/4">
  <h2>
    Velkommen til Online, linjeforeningen for <Link href="https://www.ntnu.no/studier/bit" external
      >informatikkstudenter ved NTNU</Link
    >!
  </h2>

  <div>
    Det er vi som sørger for at studietiden blir den beste tiden i ditt liv! Vi i Online arrangerer utflukter, turer,
    fester, holder kurs og bedriftspresentasjoner gjennom hele året.
  </div>

  <div>
    Vi har samlet litt info for nye informatikere. Ta en titt på <Link
      external
      href="https://online.ntnu.no/wiki/online/ny-paa-informatikk/">wiki-siden</Link
    > for å sjekke den ut!
  </div>

  <div>
    Ny på master? <Link href="https://online.ntnu.no/events/1802" external>Klikk her</Link> for viktig info om IT-ekskursjonen.
    OBS - kort frist!
  </div>

  <Link href="#events">Hopp til program!</Link>
</div>

<style>
  h2 {
    @apply text-blue-12 text-center text-4xl font-bold;
  }
</style>
